linters:
  enable:
    - gofmt
    - govet
    - golint
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - unconvert
    - misspell
    - gocritic

run:
  deadline: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

  errcheck:
    check-type-assertions: true

  govet:
    check-shadowing: true

  golint:
    min-confidence: 0.8
