linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - revive
    - gocyclo
    - nakedret
    - misspell
    - prealloc
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
  gocyclo:
    min-complexity: 15
  nakedret:
    max-func-lines: 30

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: cmd/
      linters:
        - gocyclo
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
