name: CI/CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: make setup

      - name: Run tests with race detection
        run: make test-race

      - name: Run linter
        run: make lint

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.html

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: make build

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: bin/git-branch-delete

  release:
    name: Release
    needs: [test, build]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build release
        run: make release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/git-branch-delete_*
            bin/checksums.txt
          draft: false
          prerelease: false
          generate_release_notes: true
